name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  tests:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - operating-system: 'ubuntu-latest'
            php-version: 8.1
            composer-flags: '--ignore-platform-req=php+'
          - operating-system: 'ubuntu-latest'
            php-version: 8.2
            composer-flags: '--ignore-platform-req=php+'
          - operating-system: 'ubuntu-latest'
            php-version: 8.3
            composer-flags: '--ignore-platform-req=php+'
          - operating-system: 'ubuntu-latest'
            php-version: 8.4
            composer-flags: '--ignore-platform-req=php+'
            psalm: none
          - operating-system: 'ubuntu-latest'
            php-version: 8.5
            composer-flags: '--ignore-platform-req=php+'
            psalm: none

    name: PHP ${{ matrix.php-version }} ${{ matrix.job-description }}
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libuv1-dev libevent-dev

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: uv-amphp/ext-uv@master, ev-beta, event, :xdebug

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-dir)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}-${{ matrix.composer-flags }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}-
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: Install dependencies
        run: |
          composer update --optimize-autoloader --no-interaction --no-progress ${{ matrix.composer-flags }}
          php -v
          composer info -D

      - name: Run tests
        run: php vendor/bin/phpunit

      - name: Run tests without pcntl
        run: php -d disable_functions=pcntl_signal_dispatch vendor/bin/phpunit

      - name: Run Psalm
        run: vendor/bin/psalm.phar --show-info=true
        if: matrix.psalm != 'none'

      - name: Run style fixer
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
        run: |
          composer install --optimize-autoloader --no-interaction --no-progress --working-dir=tools/php-cs-fixer
          tools/php-cs-fixer/vendor/bin/php-cs-fixer --diff --dry-run -v fix
